# Generated by Django 4.2.3 on 2024-06-11 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityParticipator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.CharField(max_length=30, null=True)),
                ("start_time_hours", models.IntegerField()),
                ("end_time", models.CharField(max_length=30, null=True)),
                ("end_time_hours", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreateActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "activity_name",
                    models.TextField(default="UnnamedActivity", max_length=30),
                ),
                ("activity_level", models.IntegerField()),
                ("activity_type", models.TextField(max_length=50)),
                ("activity_description", models.TextField(blank=True)),
                ("activity_budget", models.IntegerField()),
                ("activity_condition", models.BooleanField(default=False)),
                ("activity_place", models.CharField(default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("personal_number", models.CharField(editable=False, max_length=9)),
                ("activity_id", models.CharField(default="", max_length=100)),
                ("title", models.TextField(default="Unnamed Notice", max_length=100)),
                ("content", models.TextField(max_length=300)),
                ("type", models.CharField(default="system", max_length=30)),
                ("condition", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="TimeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.CharField(max_length=30, null=True)),
                ("start_time_hours", models.IntegerField()),
                ("end_time", models.CharField(max_length=30, null=True)),
                ("end_time_hours", models.IntegerField()),
                ("option", models.CharField(max_length=50)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_options",
                        to="activities_organization.createactivity",
                        to_field="activity_id",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
