# Generated by Django 4.2.3 on 2024-05-31 16:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityParticipator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.CharField(max_length=30, null=True)),
                ("start_time_hours", models.IntegerField()),
                ("end_time", models.CharField(max_length=30, null=True)),
                ("end_time_hours", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom_id",
                    models.CharField(editable=False, max_length=3, unique=True),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CreateActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "activity_name",
                    models.TextField(default="UnnamedActivity", max_length=30),
                ),
                ("activity_level", models.IntegerField()),
                ("activity_type", models.TextField(max_length=50)),
                ("activity_description", models.TextField(blank=True)),
                ("activity_budget", models.IntegerField()),
                ("activity_condition", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_number",
                    models.CharField(default="000000000", editable=False, max_length=9),
                ),
                ("content", models.TextField(max_length=200)),
                ("is_active", models.BooleanField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name="TimeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.CharField(max_length=30, null=True)),
                ("start_time_hours", models.IntegerField()),
                ("end_time", models.CharField(max_length=30, null=True)),
                ("end_time_hours", models.IntegerField()),
                ("option", models.CharField(max_length=50)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_options",
                        to="activities_organization.createactivity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
