# Generated by Django 4.2.3 on 2024-06-14 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities_organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="createactivity",
            name="activity_guest",
            field=models.ManyToManyField(
                blank=True,
                related_name="guest",
                through="activities_organization.ActivityGuest",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="createactivity",
            name="activity_leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="personal_number",
            ),
        ),
        migrations.AddField(
            model_name="createactivity",
            name="activity_participator",
            field=models.ManyToManyField(
                blank=True,
                related_name="participator",
                through="activities_organization.ActivityParticipator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activitytime",
            name="activity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_time",
                to="activities_organization.createactivity",
                to_field="activity_id",
            ),
        ),
        migrations.AddField(
            model_name="activityparticipator",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="activities_organization.createactivity",
                to_field="activity_id",
            ),
        ),
        migrations.AddField(
            model_name="activityparticipator",
            name="participator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="personal_number",
            ),
        ),
        migrations.AddField(
            model_name="activityguest",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="activities_organization.createactivity",
                to_field="activity_id",
            ),
        ),
        migrations.AddField(
            model_name="activityguest",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="personal_number",
            ),
        ),
    ]
