# Generated by Django 4.2.3 on 2024-05-28 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("activities_organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personal_number",
                    models.CharField(default="000000000", editable=False, max_length=9),
                ),
                ("content", models.TextField(max_length=200)),
                ("is_active", models.BooleanField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name="creatactivity",
            name="activity_admin",
        ),
        migrations.AddField(
            model_name="creatactivity",
            name="activity_guest",
            field=models.ManyToManyField(
                blank=True, related_name="guest", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="creatactivity",
            name="activity_participator",
            field=models.ManyToManyField(
                blank=True, related_name="participator", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
