# Generated by Django 4.2.3 on 2024-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities_organization", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityguest",
            name="guest_condition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activityparticipator",
            name="p_condition",
            field=models.BooleanField(default=False),
        ),
    ]
