# Generated by Django 4.2.3 on 2024-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activities_organization",
            "0002_notice_remove_creatactivity_activity_admin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="creatactivity",
            name="activity_condition",
            field=models.BooleanField(default=False),
        ),
    ]
