# Generated by Django 4.2.3 on 2024-06-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities_organization", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="createactivity",
            name="activity_condition",
            field=models.IntegerField(default=1),
        ),
    ]
