# Generated by Django 4.2.3 on 2024-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities_organization", "0003_creatactivity_activity_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="creatactivity",
            name="activity_name",
            field=models.TextField(default="UnnamedActivity", max_length=30),
        ),
    ]
