# Generated by Django 4.2.3 on 2024-06-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities_organization", "0004_alter_activitytime_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notice",
            name="is_active",
        ),
        migrations.AddField(
            model_name="notice",
            name="type",
            field=models.CharField(default="system", max_length=30),
        ),
        migrations.AlterField(
            model_name="notice",
            name="personal_number",
            field=models.CharField(editable=False, max_length=9, unique=True),
        ),
    ]
