# Generated by Django 4.2.3 on 2024-06-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activities_organization",
            "0005_remove_notice_is_active_notice_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="title",
            field=models.TextField(default="Unnamed Notice", max_length=100),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content",
            field=models.TextField(max_length=300),
        ),
    ]
