# Generated by Django 4.2.3 on 2024-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities_organization", "0006_notice_title_alter_notice_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="condition",
            field=models.BooleanField(default=True),
        ),
    ]
