# Generated by Django 4.2.3 on 2024-06-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities_organization", "0007_notice_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="notice",
            name="activity_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
