# Generated by Django 4.2.3 on 2024-06-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities_organization", "0008_notice_activity_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="personal_number",
            field=models.CharField(editable=False, max_length=9),
        ),
    ]
