# Generated by Django 4.2.3 on 2024-06-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities_organization", "0009_alter_notice_personal_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="createactivity",
            name="activity_place",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.DeleteModel(
            name="Classroom",
        ),
    ]
