# Generated by Django 4.2.3 on 2024-05-27 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreatActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("activity_level", models.IntegerField()),
                ("activity_type", models.TextField(max_length=50)),
                ("activity_description", models.TextField(blank=True)),
                ("activity_budget", models.IntegerField()),
                (
                    "activity_admin",
                    models.ManyToManyField(
                        blank=True, related_name="admin", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "activity_leader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time_day", models.IntegerField()),
                ("start_time_hours", models.IntegerField()),
                ("end_time_day", models.IntegerField()),
                ("end_time_hours", models.IntegerField()),
                ("option", models.CharField(max_length=50)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities_orgnization.creatactivity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classroom_id",
                    models.CharField(editable=False, max_length=3, unique=True),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities_orgnization.creatactivity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time_day", models.IntegerField()),
                ("start_time_hours", models.IntegerField()),
                ("end_time_day", models.IntegerField()),
                ("end_time_hours", models.IntegerField()),
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities_orgnization.creatactivity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
