# Generated by Django 4.2.3 on 2024-05-31 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities_organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=500)),
                ("file_size", models.DecimalField(decimal_places=0, max_digits=10)),
                ("file_path", models.CharField(max_length=500)),
                (
                    "active",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activities_organization.createactivity",
                    ),
                ),
            ],
        ),
    ]
