# Generated by Django 4.2.3 on 2024-05-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_and_register", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
