# Generated by Django 4.2.3 on 2024-05-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_and_register", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="personal_number",
            field=models.CharField(default="000000000", editable=False, max_length=9),
        ),
    ]
