# Generated by Django 4.2.3 on 2024-06-16 15:02

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("role", models.CharField(max_length=255)),
                (
                    "satisfaction",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("suggestions", models.TextField(default="")),
            ],
        ),
    ]
