# Generated by Django 4.2.3 on 2024-06-17 08:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("activity_feedback", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("people_num", models.IntegerField(default=0)),
                ("chat_num", models.IntegerField(default=0)),
                ("notice_num", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="feedback",
            name="activity_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
